# Generated by Django 6.0 on 2025-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
